[general]
import = ["themes/noctalia.toml"]

[terminal] 
shell = "/usr/bin/bash"

[env]
TERM = "tmux-256color"

[font]
normal = { family = "Overpass Mono", style = "Regular" }
size = 16

[window]
padding = { x = 4, y = 4 }
dynamic_padding = true
opacity = 0.95
blur = true
